apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
data:
  db-password: OGUwNDdCJWEhOWZkMmJe # 8e047B!9fd2b^
  db-user: d2ViLWxpYi11c2Vy # web-lib-user
  db-root-password: UnlORyNyRTRAOXheT1hoZQ== # RyNG#rE4@9x^OXhe
