apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: db-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: db-root-password
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-db-configmap
              key: db-host
        - name: MYSQL_TCP_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-db-configmap
              key: db-port
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-db-configmap
              key: db-name

